USE finals_db;

CREATE TABLE psgc_levels ( LEVEL_ID INT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(256) NOT NULL );

CREATE TABLE genders ( GENDER_ID INT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(256) NOT NULL );

CREATE TABLE nationalities ( NATIONALITY_ID INT AUTO_INCREMENT PRIMARY KEY, COUNTRY VARCHAR(256) NOT NULL, NATIONALITY VARCHAR(256) NOT NULL );

CREATE TABLE degree_types ( TYPE_ID INT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(256) NOT NULL );

CREATE TABLE titles ( TITLE_ID INT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(512) NOT NULL );

CREATE TABLE departments ( DEPARTMENT_ID INT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(512) NOT NULL );

CREATE TABLE degrees ( DEGREE_CODE INT AUTO_INCREMENT PRIMARY KEY, TYPE_ID INT NOT NULL, DEPARTMENT_ID INT NOT NULL, FOREIGN KEY (TYPE_ID) REFERENCES degree_types(TYPE_ID), FOREIGN KEY (DEPARTMENT_ID) REFERENCES departments(DEPARTMENT_ID) );

CREATE TABLE psgc_codes ( PSGC_CODE CHAR(10) PRIMARY KEY NOT NULL, NAME VARCHAR(1024) NOT NULL, LEVEL_ID INT NOT NULL, FOREIGN KEY (LEVEL_ID) REFERENCES psgc_levels(LEVEL_ID) );

CREATE TABLE classrooms ( CLASSROOM_ID VARCHAR(20) PRIMARY KEY NOT NULL, CAPACITY INT NOT NULL );

CREATE TABLE professors ( EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY, FIRST_NAME VARCHAR(512) NOT NULL, LAST_NAME VARCHAR(512) NOT NULL, DEPARTMENT_ID INT NOT NULL, HIRE_DATE DATE NOT NULL, TITLE_ID INT NOT NULL, FOREIGN KEY (DEPARTMENT_ID) REFERENCES departments(DEPARTMENT_ID), FOREIGN KEY (TITLE_ID) REFERENCES titles(TITLE_ID) );

CREATE TABLE students ( STUDENT_ID INT AUTO_INCREMENT PRIMARY KEY, FIRST_NAME VARCHAR(256) NOT NULL, LAST_NAME VARCHAR(256) NOT NULL, BIRTH_DATE DATE NOT NULL, GENDER_ID INT NOT NULL, EMAIL_ADDRESS VARCHAR(256) NOT NULL, CONTACT_NUMBER VARCHAR(20) NOT NULL, NATIONALITY_ID INT NOT NULL, ADDRESS_REGION_CODE CHAR(10) NOT NULL, ADDRESS_PROVINCE_CODE CHAR(10) NOT NULL, ADDRESS_MUNICIPALITY_CITY_CODE CHAR(10) NOT NULL, ADDRESS_BARANGAY_CODE CHAR(10) NOT NULL, ADDRESS_STREET VARCHAR(512) NOT NULL, DEGREE_CODE INT NOT NULL, FOREIGN KEY (GENDER_ID) REFERENCES genders(GENDER_ID), FOREIGN KEY (NATIONALITY_ID) REFERENCES nationalities(NATIONALITY_ID), FOREIGN KEY (ADDRESS_REGION_CODE) REFERENCES psgc_codes(PSGC_CODE), FOREIGN KEY (ADDRESS_PROVINCE_CODE) REFERENCES psgc_codes(PSGC_CODE), FOREIGN KEY (ADDRESS_MUNICIPALITY_CITY_CODE) REFERENCES psgc_codes(PSGC_CODE), FOREIGN KEY (ADDRESS_BARANGAY_CODE) REFERENCES psgc_codes(PSGC_CODE), FOREIGN KEY (DEGREE_CODE) REFERENCES degrees(DEGREE_CODE) );

CREATE TABLE course_codes ( COURSE_CODE INT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(256) NOT NULL, DESCRIPTION VARCHAR(2048) NOT NULL, DEPARTMENT_ID INT NOT NULL, UNITS INT NOT NULL, FOREIGN KEY (DEPARTMENT_ID) REFERENCES departments(DEPARTMENT_ID) );

CREATE TABLE time_blocks ( block_id INT PRIMARY KEY, block_time_start TIME NOT NULL, block_time_end TIME NOT NULL );

CREATE TABLE classes ( class_number INT PRIMARY KEY, course_code INT NOT NULL, professor_id INT NOT NULL, school_year INT NOT NULL, semester INT NOT NULL, schedule CHAR(7) NOT NULL, time_block_start int NOT NULL, time_block_end INT NOT NULL, FOREIGN KEY (course_code) REFERENCES course_codes(COURSE_CODE), FOREIGN KEY (professor_id) REFERENCES professors(EMPLOYEE_ID), FOREIGN KEY (time_block_start) REFERENCES time_blocks(block_id), FOREIGN KEY (time_block_end) REFERENCES time_blocks(block_id) );

CREATE TABLE enrollments ( Class_number INT NOT NULL, Student_id INT NOT NULL, FOREIGN KEY (Class_number) REFERENCES classes(Class_number), FOREIGN KEY (Student_id) REFERENCES students(Student_id) );
