INSERT INTO course_codes (name, description, department_id, units)
VALUES
('Introduction to Computer Science', 'Lorem ipsum dolor sit amet...', 1, 3),
('Digital Logic Design', 'Lorem ipsum dolor sit amet...', 1, 3),
('Circuit Theory', 'Lorem ipsum dolor sit amet...', 2, 3),
('Electromagnetics', 'Lorem ipsum dolor sit amet...', 2, 3),
('Mechanics of Solids', 'Lorem ipsum dolor sit amet...', 3, 3),
('Fluid Mechanics', 'Lorem ipsum dolor sit amet...', 3, 3),
('Calculus I', 'Lorem ipsum dolor sit amet...', 5, 3),
('Linear Algebra', 'Lorem ipsum dolor sit amet...', 5, 3),
('General Chemistry', 'Lorem ipsum dolor sit amet...', 7, 3),
('Organic Chemistry', 'Lorem ipsum dolor sit amet...', 7, 3),
('General Biology', 'Lorem ipsum dolor sit amet...', 8, 3),
('Anatomy and Physiology', 'Lorem ipsum dolor sit amet...', 8, 3),
('General Psychology', 'Lorem ipsum dolor sit amet...', 9, 3),
('Social Psychology', 'Lorem ipsum dolor sit amet...', 9, 3),
('Introduction to Sociology', 'Lorem ipsum dolor sit amet...', 10, 3),
('Social Inequality', 'Lorem ipsum dolor sit amet...', 10, 3),
('World History', 'Lorem ipsum dolor sit amet...', 11, 3),
('Philippine History', 'Lorem ipsum dolor sit amet...', 11, 3),
('English Composition', 'Lorem ipsum dolor sit amet...', 12, 3),
('Creative Writing', 'Lorem ipsum dolor sit amet...', 12, 3),
('Microeconomics', 'Lorem ipsum dolor sit amet...', 13, 3),
('Macroeconomics', 'Lorem ipsum dolor sit amet...', 13, 3),
('Principles of Accounting', 'Lorem ipsum dolor sit amet...', 14, 3),
('Financial Accounting', 'Lorem ipsum dolor sit amet...', 14, 3),
('Corporate Finance', 'Lorem ipsum dolor sit amet...', 16, 3),
('Investment Analysis', 'Lorem ipsum dolor sit amet...', 16, 3),
('Principles of Marketing', 'Lorem ipsum dolor sit amet...', 17, 3),
('Marketing Management', 'Lorem ipsum dolor sit amet...', 17, 3),
('Human Resource Management', 'Lorem ipsum dolor sit amet...', 18, 3),
('Organizational Behavior', 'Lorem ipsum dolor sit amet...', 18, 3),
('Introduction to Information Systems', 'Lorem ipsum dolor sit amet...', 19, 3),
('Database Systems', 'Lorem ipsum dolor sit amet...', 19, 3),
('Introduction to Philosophy', 'Lorem ipsum dolor sit amet...', 20, 3),
('Ethics', 'Lorem ipsum dolor sit amet...', 20, 3),
('American Politics', 'Lorem ipsum dolor sit amet...', 21, 3),
('International Relations', 'Lorem ipsum dolor sit amet...', 21, 3),
('Art Appreciation', 'Lorem ipsum dolor sit amet...', 22, 3),
('Art History', 'Lorem ipsum dolor sit amet...', 22, 3),
('Music Theory', 'Lorem ipsum dolor sit amet...', 23, 3),
('Music History', 'Lorem ipsum dolor sit amet...', 23, 3),
('Elementary Spanish', 'Lorem ipsum dolor sit amet...', 24, 3),
('Intermediate Spanish', 'Lorem ipsum dolor sit amet...', 24, 3),
('Foundations of Education', 'Lorem ipsum dolor sit amet...', 25, 3),
('Curriculum Development', 'Lorem ipsum dolor sit amet...', 25, 3),
('Fundamentals of Nursing', 'Lorem ipsum dolor sit amet...', 26, 3),
('Medical-Surgical Nursing', 'Lorem ipsum dolor sit amet...', 26, 3),
('Legal Ethics', 'Lorem ipsum dolor sit amet...', 27, 3),
('Constitutional Law', 'Lorem ipsum dolor sit amet...', 27, 3);