CREATE VIEW V_CLASSES AS

SELECT CLASS_NUMBER
,COURSE_CODES.NAME AS COURSE_NAME
,CONCAT(PROFESSORS.FIRST_NAME,' ',PROFESSORS.LAST_NAME) AS PROFESSOR
,SCHOOL_YEAR
,SEMESTER
,SCHEDULE
,TIME_START.BLOCK_TIME_START AS TIME_START
,TIME_END.BLOCK_TIME_START AS TIME_END
,CLASSROOM_ID AS CLASSROOM
FROM CLASSES
LEFT JOIN COURSE_CODES ON CLASSES.COURSE_CODE = COURSE_CODES.COURSE_CODE
LEFT JOIN PROFESSORS ON CLASSES.PROFESSOR_ID = PROFESSORS.EMPLOYEE_ID
LEFT JOIN TIME_BLOCKS TIME_START ON CLASSES.TIME_BLOCK_START = TIME_START.BLOCK_ID
LEFT JOIN TIME_BLOCKS TIME_END ON CLASSES.TIME_BLOCK_END = TIME_END.BLOCK_ID