CREATE VIEW V_ENROLLMENTS AS

SELECT ENROLLMENTS.STUDENT_ID
,CONCAT(STUDENTS.FIRST_NAME,' ',STUDENTS.LAST_NAME) AS STUDENT_NAME
,ENROLLMENTS.CLASS_NUMBER AS CLASS_NUMBER
,COURSE_CODES.NAME AS COURSE_NAME
,SCHOOL_YEAR
,SEMESTER
FROM ENROLLMENTS
LEFT JOIN STUDENTS ON ENROLLMENTS.STUDENT_ID = STUDENTS.STUDENT_ID
LEFT JOIN CLASSES ON ENROLLMENTS.CLASS_NUMBER = CLASSES.CLASS_NUMBER
LEFT JOIN COURSE_CODES ON CLASSES.COURSE_CODE = COURSE_CODES.COURSE_CODE
