CREATE VIEW V_STUDENTS AS

SELECT 
STUDENT_ID AS ID_NUMBER
,FIRST_NAME 
,LAST_NAME
,BIRTH_DATE
,GENDERS.NAME AS GENDER
,EMAIL_ADDRESS
,CONTACT_NUMBER
,NATIONALITIES.COUNTRY AS NATIONALITY
,CONCAT(DEGREE_TYPES.NAME,' in ',DEGREES.NAME) AS DEGREE_PROGRAM
,STUDENT_STATUS
FROM STUDENTS
LEFT JOIN GENDERS ON STUDENTS.GENDER_ID = GENDERS.GENDER_ID
LEFT JOIN NATIONALITIES ON STUDENTS.NATIONALITY_ID = NATIONALITIES.NATIONALITY_ID
LEFT JOIN DEGREES ON STUDENTS.DEGREE_CODE = DEGREES.DEGREE_CODE
LEFT JOIN DEGREE_TYPES ON DEGREES.TYPE_ID = DEGREE_TYPES.TYPE_ID